print (3**2)
print(type(10))
print(type(2.7))
print(type("hello"))
import numpy as np
x = np.array([1.0, 2, 3])
print(x)
print(type(x))
y = np.array([2.0, 4, 6])
print(y)
print(x + y)
print(x - y)
print(x * y)
print(x / y)
import matplotlib.pyplot as plt
x = np.arange(0, 6, 0.1)
y = np.sin(x)
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 0], [0, 6]])
print(A)
print(A.shape)
print(A.dtype)
print(A + B)
print(A * B)
print(A * 100)
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)
print(X[0][1])
print(X.shape)
Y = X.flatten()
print(Y)
print(Y.shape)
Z = Y > 15
print(Z)
print(Y[Y > 15])